name: 'pr'
on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: Build, Test, Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build --configuration=production

      - name: Test
        run: pnpm test

      - name: Lint
        run: pnpm lint
